
SOURCES= \
    apppath.cpp \
    dragimage.cpp \
    eljaccelerator.cpp \
    eljartprov.cpp \
    eljbitmap.cpp \
    eljbrush.cpp \
    eljbusyinfo.cpp \
    eljbutton.cpp \
    eljcalendarctrl.cpp \
    eljcaret.cpp \
    eljcheckbox.cpp \
    eljchecklistbox.cpp \
    eljchoice.cpp \
    eljclipboard.cpp \
    eljcoldata.cpp \
    eljcolour.cpp \
    eljcolourdlg.cpp \
    eljcombobox.cpp \
    eljconfigbase.cpp \
    eljcontrol.cpp \
    eljctxhelp.cpp \
    eljcursor.cpp \
    eljdataformat.cpp \
    eljdatetime.cpp \
    eljdc.cpp \
    eljdcsvg.cpp \
    eljdialog.cpp \
    eljdirdlg.cpp \
    eljdnd.cpp \
    eljdrawing.cpp \
    eljevent.cpp \
    eljfiledialog.cpp \
    eljfilehist.cpp \
    eljfindrepldlg.cpp \
    eljfont.cpp \
    eljfontdata.cpp \
    eljfontdlg.cpp \
    eljframe.cpp \
    eljgauge.cpp \
    eljgrid.cpp \
    eljhelpcontroller.cpp \
    eljicnbndl.cpp \
    eljicon.cpp \
    eljimage.cpp \
    eljimagelist.cpp \
    eljlayoutconstraints.cpp \
    eljlistbox.cpp \
    eljlistctrl.cpp \
    eljlocale.cpp \
    eljlog.cpp \
    eljmask.cpp \
    eljmdi.cpp \
    eljmenu.cpp \
    eljmenubar.cpp \
    eljmessagedialog.cpp \
    eljmime.cpp \
    eljminiframe.cpp \
    eljnotebook.cpp \
    eljpalette.cpp \
    eljpanel.cpp \
    eljpen.cpp \
    eljprintdlg.cpp \
    eljprinting.cpp \
    eljprocess.cpp \
    eljradiobox.cpp \
    eljradiobutton.cpp \
    eljrc.cpp \
    eljregion.cpp \
    eljregioniter.cpp \
    eljsash.cpp \
    eljscrollbar.cpp \
    eljscrolledwindow.cpp \
    eljsingleinst.cpp \
    eljsizer.cpp \
    eljslider.cpp \
    eljspinctrl.cpp \
    eljsplitterwindow.cpp \
    eljstaticbox.cpp \
    eljstaticline.cpp \
    eljstatictext.cpp \
    eljstatusbar.cpp \
    eljsystemsettings.cpp \
    eljtextctrl.cpp \
    eljtimer.cpp \
    eljtipwnd.cpp \
    eljtoolbar.cpp \
    eljvalidator.cpp \
    eljwindow.cpp \
    eljwizard.cpp \
    ewxw_main.cpp \
    extra.cpp \
    glcanvas.cpp \
    graphicscontext.cpp \
    image.cpp \
    managed.cpp \
    mediactrl.cpp \
    previewframe.cpp \
    printout.cpp \
    sckaddr.cpp \
    socket.cpp \
    sound.cpp \
    stc.cpp \
    std.cpp \
    taskbaricon.cpp \
    textstream.cpp \
    treectrl.cpp \
    defs.cpp \
    wrapper.cpp 

#    stc_gen.cpp ?


OBJECTS=$(SOURCES:.cpp=.o)

target: liblwc.so

liblwc.so: $(OBJECTS)
	/usr/bin/gcc -g -Wl,--hash-size=31 -Wl,--reduce-memory-overheads -shared -Wl,-soname,libwxc.so -o libwxc.so $(OBJECTS) -L/usr/local/lib -lstdc++ -lwx_gtk2u_xrc-2.9 -lwx_gtk2u_stc-2.9 -lwx_gtk2u_richtext-2.9 -lwx_gtk2u_ribbon-2.9 -lwx_gtk2u_propgrid-2.9 -lwx_gtk2u_aui-2.9 -lwx_gtk2u_gl-2.9 -lwx_gtk2u_html-2.9 -lwx_gtk2u_qa-2.9 -lwx_gtk2u_adv-2.9 -lwx_gtk2u_core-2.9 -lwx_baseu_xml-2.9 -lwx_baseu_net-2.9 -lwx_baseu-2.9


.cpp.o:
	/usr/bin/gcc -g -Wl,--hash-size=31 -Wl,--reduce-memory-overheads -Isrc/include -I/usr/local/include/wx-2.9 -I/usr/local/lib/wx/include/gtk2-unicode-2.9 -D__WXGTK__ -DWXUSINGDLL -D_FILE_OFFSET_BITS=64 -DwxcREFUSE_MEDIACTRL -fPIC -c $< -o $@

