type wxRect = int * int * int * int
type wxPoint = int * int
type wxSize = int * int
type wxString = string
type ints = int array
type wxAcceleratorTable
type wxActivateEvent
type wxAnyButton
type wxBitmap
type wxBitmapButton
type wxBoxSizer
type wxButton
type wxCaret
type wxChildFocusEvent
type wxClipboardTextEvent
type wxCloseEvent
type wxColour
type wxCommandEvent
type wxContextMenuEvent
type wxControl
type wxCursor
type wxDC
type wxDisplayChangedEvent
type wxDragImage
type wxDropFilesEvent
type wxDropTarget
type wxEraseEvent
type wxEvent
type wxEvtHandler
type wxFlexGridSizer
type wxFocusEvent
type wxFont
type wxFrame
type wxGenericDragImage
type wxGridSizer
type wxHelpEvent
type wxIcon
type wxIconBundle
type wxIconizeEvent
type wxIdleEvent
type wxInitDialogEvent
type wxJoystickEvent
type wxKeyEvent
type wxLayoutConstraints
type wxListCtrl
type wxMaximizeEvent
type wxMemoryDC
type wxMenu
type wxMenuBar
type wxMenuEvent
type wxMenuItem
type wxMouseCaptureChangedEvent
type wxMouseCaptureLostEvent
type wxMouseEvent
type wxMoveEvent
type wxNavigationKeyEvent
type wxNcPaintEvent
type wxNonOwnedWindowBase
type wxObject
type wxPaintEvent
type wxPaletteChangedEvent
type wxPanel
type wxQueryNewPaletteEvent
type wxRegion
type wxScrollEvent
type wxScrollWinEvent
type wxSetCursorEvent
type wxShowEvent
type wxSizeEvent
type wxSizer
type wxSizerItem
type wxSpinEvent
type wxStaticBox
type wxStaticBoxSizer
type wxStaticText
type wxStatusBar
type wxSysColourChangedEvent
type wxThreadEvent
type wxToolBar
type wxToolTip
type wxTopLevelWindow
type wxTopLevelWindowBase
type wxTreeCtrl
type wxTreeItemId
type wxUpdateUIEvent
type wxValidator
type wxWindow
type wxWindowBase
type wxWindowCreateEvent
type wxWindowDestroyEvent
