#*******************************************************************#
#*                                                                 *#
#*                            wxOCaml                              *#
#*                                                                 *#
#*                       Fabrice LE FESSANT                        *#
#*                                                                 *#
#*                 Copyright 2013, INRIA/OCamlPro.                 *#
#*            Licence LGPL v3.0 with linking exception.            *#
#*                                                                 *#
#*******************************************************************#

# Generated sources cannot be linked, since they have dependencies towards
# the OCaml runtime :-(

include Makefile.project

include ../config/Makefile


all: 

clean:
	rm -f *.o *~ generated \
           $(GENERATED_OCAML_SOURCES) build.ocpgen \
           Makefile.project  wxHAS.ml wxUSE.ml

