#*******************************************************************#
#*                                                                 *#
#*                            wxOCaml                              *#
#*                                                                 *#
#*                       Fabrice LE FESSANT                        *#
#*                                                                 *#
#*                 Copyright 2013, INRIA/OCamlPro.                 *#
#*            Licence LGPL v3.0 with linking exception.            *#
#*                                                                 *#
#*******************************************************************#

all: $(TARGETS)

clean:
	rm -f *~ gen_wxDefs gen_wxDefs.cpp gen.o *.cm? \
             genWxHAS.cpp genWxUSE.cpp wxUSE.ml wxDefs.ml wxHAS.ml

