type wxRect = int * int * int * int
type wxPoint = int * int
type wxSize = int * int
type wxString = string
type ints = int array
type wxAcceleratorTable
type wxActivateEvent
type wxAnyButton
type wxApp
type wxAppConsole
type wxBitmap
type wxBitmapButton
type wxBoxSizer
type wxButton
type wxCalendarCtrl
type wxCalendarDateAttr
type wxCalendarEvent
type wxCaret
type wxChildFocusEvent
type wxClipboardTextEvent
type wxCloseEvent
type wxColour
type wxCommandEvent
type wxContextMenuEvent
type wxControl
type wxCursor
type wxDC
type wxDateEvent
type wxDateTime
type wxDialog
type wxDisplayChangedEvent
type wxDragImage
type wxDropFilesEvent
type wxDropTarget
type wxEraseEvent
type wxEvent
type wxEvtHandler
type wxFlexGridSizer
type wxFocusEvent
type wxFont
type wxFrame
type wxGenericDragImage
type wxGridSizer
type wxHelpEvent
type wxIcon
type wxIconBundle
type wxIconizeEvent
type wxIdleEvent
type wxInitDialogEvent
type wxJoystickEvent
type wxKeyEvent
type wxKeyboardState
type wxLayoutConstraints
type wxListCtrl
type wxLog
type wxLogChain
type wxLogInterposer
type wxLogNull
type wxLogStderr
type wxLogTextCtrl
type wxLogWindow
type wxMaximizeEvent
type wxMemoryDC
type wxMenu
type wxMenuBar
type wxMenuEvent
type wxMenuItem
type wxMisc
type wxMouseCaptureChangedEvent
type wxMouseCaptureLostEvent
type wxMouseEvent
type wxMouseState
type wxMoveEvent
type wxNavigationKeyEvent
type wxNcPaintEvent
type wxNonOwnedWindowBase
type wxObject
type wxPaintEvent
type wxPaletteChangedEvent
type wxPanel
type wxQueryNewPaletteEvent
type wxRegion
type wxScrollEvent
type wxScrollWinEvent
type wxSetCursorEvent
type wxShowEvent
type wxSizeEvent
type wxSizer
type wxSizerItem
type wxSpinEvent
type wxSplitterWindow
type wxStaticBox
type wxStaticBoxSizer
type wxStaticText
type wxStatusBar
type wxSysColourChangedEvent
type wxSystemSettings
type wxTextCtrl
type wxTextEntry
type wxThreadEvent
type wxToolBar
type wxToolTip
type wxTopLevelWindow
type wxTopLevelWindowBase
type wxTreeCtrl
type wxTreeItemId
type wxUpdateUIEvent
type wxValidator
type wxWindow
type wxWindowBase
type wxWindowCreateEvent
type wxWindowDestroyEvent
