typedef wxArray wxArrayString;
typedef wxClientData wxStringClientData;
typedef wxClientData wxTreeItemData;
typedef wxTreeItemData wxcTreeItemData;
typedef wxDataObject wxDataObjectComposite;
typedef wxDataObject wxDataObjectSimple;
typedef wxDataObjectSimple wxBitmapDataObject;
typedef wxDataObjectSimple wxCustomDataObject;
typedef wxDataObjectSimple wxFileDataObject;
typedef wxDataObjectSimple wxTextDataObject;
typedef wxDropTarget ELJDropTarget;
typedef wxDropTarget wxFileDropTarget;
typedef wxDropTarget wxPrivateDropTarget;
typedef wxDropTarget wxTextDropTarget;
typedef wxFileDropTarget ELJFileDropTarget;
typedef wxTextDropTarget ELJTextDropTarget;
typedef wxGridCellWorker wxGridCellEditor;
typedef wxGridCellWorker wxGridCellRenderer;
typedef wxGridCellEditor wxGridCellBoolEditor;
typedef wxGridCellEditor wxGridCellChoiceEditor;
typedef wxGridCellEditor wxGridCellTextEditor;
typedef wxGridCellTextEditor wxGridCellFloatEditor;
typedef wxGridCellTextEditor wxGridCellNumberEditor;
typedef wxGridCellRenderer wxGridCellBoolRenderer;
typedef wxGridCellRenderer wxGridCellStringRenderer;
typedef wxGridCellStringRenderer wxGridCellFloatRenderer;
typedef wxGridCellStringRenderer wxGridCellNumberRenderer;
typedef wxGridCellStringRenderer wxGridCellAutoWrapStringRenderer;
typedef wxHelpProvider wxSimpleHelpProvider;
typedef wxSimpleHelpProvider wxHelpControllerHelpProvider;
typedef wxLocale ELJLocale;
typedef wxLog ELJLog;
typedef wxLog wxLogChain;
typedef wxLog wxLogGUI;
typedef wxLog wxLogNull;
typedef wxLog wxLogStderr;
typedef wxLog wxLogStream;
typedef wxLog wxLogTextCtrl;
typedef wxLogChain wxLogPassThrough;
typedef wxLogPassThrough wxLogWindow;
typedef wxMBConv wxCSConv;
typedef wxMBConv wxMBConvFile;
typedef wxMBConv wxMBConvUTF7;
typedef wxMBConv wxMBConvUTF8;
/*
typedef wxObject cbBarInfo;
typedef wxObject cbCommonPaneProperties;
typedef wxObject cbDimHandlerBase;
typedef wxObject cbDimInfo;
typedef wxObject cbDockPane;
typedef wxObject cbMiniButton;
typedef wxObject cbRowInfo;
typedef wxObject cbUpdatesManagerBase;
*/
typedef wxObject wxArtProvider;
typedef wxObject wxAutomationObject;
typedef wxObject wxBitmapHandler;
typedef wxObject wxClientBase;
typedef wxObject wxClipboard;
typedef wxObject wxColour;
typedef wxObject wxColourData;
typedef wxObject wxCommand;
typedef wxObject wxCommandProcessor;
typedef wxObject wxConnectionBase;
typedef wxObject wxContextHelp;
typedef wxObject wxDC;
typedef wxObject wxDatabase;
typedef wxObject wxDocTemplate;
typedef wxObject wxDragImage;
typedef wxObject wxEncodingConverter;
typedef wxObject wxEvent;
typedef wxObject wxEvtHandler;
typedef wxObject wxFSFile;
typedef wxObject wxFileHistory;
typedef wxObject wxFileSystem;
typedef wxObject wxFileSystemHandler;
typedef wxObject wxFindReplaceData;
typedef wxObject wxFontData;
typedef wxObject wxGDIObject;
typedef wxObject wxGridTableBase;
typedef wxObject wxHelpControllerBase;
typedef wxObject wxHtmlCell;
typedef wxObject wxHtmlDCRenderer;
typedef wxObject wxHtmlEasyPrinting;
typedef wxObject wxHtmlFilter;
typedef wxObject wxHtmlHelpData;
typedef wxObject wxHtmlLinkInfo;
typedef wxObject wxHtmlParser;
typedef wxObject wxHtmlTag;
typedef wxObject wxHtmlTagHandler;
typedef wxObject wxImage;
typedef wxObject wxImageHandler;
typedef wxObject wxImageList;
typedef wxObject wxIndividualLayoutConstraint;
typedef wxObject wxJoystick;
typedef wxObject wxLayoutAlgorithm;
typedef wxObject wxLayoutConstraints;
typedef wxObject wxList;
typedef wxObject wxListItem;
typedef wxObject wxMask;
typedef wxObject wxMenuItem;
typedef wxObject wxMetafile;
typedef wxObject wxModule;
typedef wxObject wxMultiCellItemHandle;
typedef wxObject wxPageSetupDialogData;
typedef wxObject wxPlotCurve;
typedef wxObject wxPlotOnOffCurve;
typedef wxObject wxPrintData;
typedef wxObject wxPrintDialogData;
typedef wxObject wxPrintPreview;
typedef wxObject wxPrinter;
typedef wxObject wxPrintout;
typedef wxObject wxQuantize;
typedef wxObject wxQueryCol;
typedef wxObject wxQueryField;
typedef wxObject wxRecordSet;
typedef wxObject wxRegionIterator;
typedef wxObject wxServerBase;
typedef wxObject wxSizer;
typedef wxObject wxSizerItem;
typedef wxObject wxSockAddress;
typedef wxObject wxSocketBase;
typedef wxObject wxStringTokenizer;
typedef wxObject wxSystemOptions;
typedef wxObject wxSystemSettings;
typedef wxObject wxTablesInUse;
typedef wxObject wxTime;
typedef wxObject wxTimer;
typedef wxObject wxTimerBase;
typedef wxObject wxToolLayoutItem;
typedef wxObject wxToolTip;
typedef wxObject wxTreeLayout;
typedef wxObject wxURL;
typedef wxObject wxVariant;
typedef wxObject wxVariantData;
typedef wxObject wxXmlResource;
typedef wxObject wxXmlResourceHandler;
typedef wxObject wxPostScriptPrintNativeData;
typedef wxObject wxPGProperty;
typedef wxPGProperty wxStringProperty;
typedef wxPGProperty wxIntProperty;
typedef wxPGProperty wxBoolProperty;
typedef wxPGProperty wxFloatProperty;
typedef wxPGProperty wxDateProperty;
typedef wxPGProperty wxFileProperty;
typedef wxPGProperty wxPropertyCategory;
/*
typedef cbDimHandlerBase cbDynToolBarDimHandler;
typedef cbMiniButton cbCloseBox;
typedef cbMiniButton cbCollapseBox;
typedef cbMiniButton cbDockBox;
typedef cbUpdatesManagerBase cbSimpleUpdatesMgr;
typedef cbSimpleUpdatesMgr cbGCUpdatesMgr;
*/
typedef wxArtProvider ELJArtProv;
typedef wxClientBase wxClient;
typedef wxClientBase wxDDEClient;
typedef wxClient ELJClient;
typedef wxCommand ELJCommand;
typedef wxConnectionBase wxConnection;
typedef wxConnectionBase wxDDEConnection;
typedef wxConnection ELJConnection;
typedef wxDC wxMemoryDC;
typedef wxDC wxMetafileDC;
typedef wxDC wxPostScriptDC;
typedef wxDC wxPrinterDC;
typedef wxDC wxSVGFileDC;
typedef wxDC wxScreenDC;
typedef wxDC wxWindowDC;
typedef wxDC wxAutoBufferedPaintDC;
typedef wxDC wxBufferedDC;
typedef wxDC wxBufferedPaintDC;
typedef wxDC wxMirrorDC;
typedef wxWindowDC wxClientDC;
typedef wxWindowDC wxPaintDC;
//typedef wxEvent cbPluginEvent;
typedef wxEvent wxActivateEvent;
typedef wxEvent wxCalculateLayoutEvent;
typedef wxEvent wxCloseEvent;
typedef wxEvent wxCommandEvent;
typedef wxEvent wxDialUpEvent;
typedef wxEvent wxDropFilesEvent;
typedef wxEvent wxEraseEvent;
typedef wxEvent wxFocusEvent;
typedef wxEvent wxIconizeEvent;
typedef wxEvent wxIdleEvent;
typedef wxEvent wxInitDialogEvent;
typedef wxEvent wxInputSinkEvent;
typedef wxEvent wxJoystickEvent;
typedef wxEvent wxKeyEvent;
typedef wxEvent wxMaximizeEvent;
typedef wxEvent wxMenuEvent;
typedef wxEvent wxMouseCaptureChangedEvent;
typedef wxEvent wxMouseEvent;
typedef wxEvent wxMoveEvent;
typedef wxEvent wxNavigationKeyEvent;
typedef wxEvent wxPaintEvent;
typedef wxEvent wxPaletteChangedEvent;
typedef wxEvent wxProcessEvent;
typedef wxEvent wxQueryLayoutInfoEvent;
typedef wxEvent wxQueryNewPaletteEvent;
typedef wxEvent wxSashEvent;
typedef wxEvent wxScrollEvent;
typedef wxEvent wxScrollWinEvent;
typedef wxEvent wxSetCursorEvent;
typedef wxEvent wxShowEvent;
typedef wxEvent wxSizeEvent;
typedef wxEvent wxSocketEvent;
typedef wxEvent wxSysColourChangedEvent;
typedef wxEvent wxTimerEvent;
typedef wxEvent wxUpdateUIEvent;
/*
typedef cbPluginEvent cbCustomizeBarEvent;
typedef cbPluginEvent cbCustomizeLayoutEvent;
typedef cbPluginEvent cbDrawBarDecorEvent;
typedef cbPluginEvent cbDrawBarHandlesEvent;
typedef cbPluginEvent cbDrawHintRectEvent;
typedef cbPluginEvent cbDrawPaneBkGroundEvent;
typedef cbPluginEvent cbDrawPaneDecorEvent;
typedef cbPluginEvent cbDrawRowBkGroundEvent;
typedef cbPluginEvent cbDrawRowDecorEvent;
typedef cbPluginEvent cbDrawRowHandlesEvent;
typedef cbPluginEvent cbFinishDrawInAreaEvent;
typedef cbPluginEvent cbInsertBarEvent;
typedef cbPluginEvent cbLayoutRowEvent;
typedef cbPluginEvent cbLeftDClickEvent;
typedef cbPluginEvent cbLeftDownEvent;
typedef cbPluginEvent cbLeftUpEvent;
typedef cbPluginEvent cbMotionEvent;
typedef cbPluginEvent cbRemoveBarEvent;
typedef cbPluginEvent cbResizeBarEvent;
typedef cbPluginEvent cbResizeRowEvent;
typedef cbPluginEvent cbRightDownEvent;
typedef cbPluginEvent cbRightUpEvent;
typedef cbPluginEvent cbSizeBarWndEvent;
typedef cbPluginEvent cbStartBarDraggingEvent;
typedef cbPluginEvent cbStartDrawInAreaEvent;
*/
typedef wxCommandEvent wxCalendarEvent;
typedef wxCommandEvent wxFindDialogEvent;
typedef wxCommandEvent wxGridEditorCreatedEvent;
typedef wxCommandEvent wxHelpEvent;
typedef wxCommandEvent wxNotifyEvent;
typedef wxCommandEvent wxTabEvent;
typedef wxCommandEvent wxWindowCreateEvent;
typedef wxCommandEvent wxWindowDestroyEvent;
typedef wxCommandEvent wxcHtmlEvent;
typedef wxNotifyEvent wxGridEvent;
typedef wxNotifyEvent wxGridRangeSelectEvent;
typedef wxNotifyEvent wxGridSizeEvent;
typedef wxNotifyEvent wxListEvent;
typedef wxNotifyEvent wxNotebookEvent;
typedef wxNotifyEvent wxPlotEvent;
typedef wxNotifyEvent wxSpinEvent;
typedef wxNotifyEvent wxSplitterEvent;
typedef wxNotifyEvent wxTreeEvent;
typedef wxNotifyEvent wxWizardEvent;
typedef wxNotifyEvent wxPropertyGridEvent;
//typedef wxEvtHandler cbBarSpy;
//typedef wxEvtHandler cbPluginBase;
typedef wxEvtHandler wxApp;
typedef wxEvtHandler wxDocManager;
typedef wxEvtHandler wxDocument;
typedef wxEvtHandler wxFrameLayout;
typedef wxEvtHandler wxMenu;
typedef wxEvtHandler wxMenuBar;
typedef wxEvtHandler wxProcess;
typedef wxEvtHandler wxTaskBarIcon;
typedef wxEvtHandler wxValidator;
typedef wxEvtHandler wxView;
typedef wxEvtHandler wxWave;
typedef wxEvtHandler wxWindow;
/*
typedef cbPluginBase cbAntiflickerPlugin;
typedef cbPluginBase cbBarDragPlugin;
typedef cbPluginBase cbBarHintsPlugin;
typedef cbPluginBase cbHintAnimationPlugin;
typedef cbPluginBase cbPaneDrawPlugin;
typedef cbPluginBase cbRowDragPlugin;
typedef cbPluginBase cbRowLayoutPlugin;
typedef cbPluginBase cbSimpleCustomizationPlugin;
*/
typedef wxApp ELJApp;
typedef wxValidator wxGenericValidator;
typedef wxValidator wxTextValidator;
typedef wxTextValidator ELJTextValidator;
typedef wxWindow wxControl;
typedef wxWindow wxDialog;
typedef wxWindow wxDrawWindow;
typedef wxWindow wxDynamicSashWindow;
typedef wxWindow wxFrame;
typedef wxWindow wxMDIClientWindow;
typedef wxWindow wxPanel;
typedef wxWindow wxPopupWindow;
typedef wxWindow wxSashWindow;
typedef wxWindow wxSplitterWindow;
typedef wxWindow wxStatusBar;
typedef wxWindow wxTreeCompanionWindow;
typedef wxWindow wxTopLevelWindow;
typedef wxControl wxButton;
typedef wxControl wxCalendarCtrl;
typedef wxControl wxCheckBox;
typedef wxControl wxChoice;
typedef wxControl wxDrawControl;
typedef wxControl wxGauge;
typedef wxControl wxGenericDirCtrl;
typedef wxControl wxLEDNumberCtrl;
typedef wxControl wxListBox;
typedef wxControl wxListCtrl;
typedef wxControl wxNotebook;
typedef wxControl wxRadioBox;
typedef wxControl wxRadioButton;
typedef wxControl wxScrollBar;
typedef wxControl wxSlider;
typedef wxControl wxSpinButton;
typedef wxControl wxSpinCtrl;
typedef wxControl wxStaticBitmap;
typedef wxControl wxStaticBox;
typedef wxControl wxStaticLine;
typedef wxControl wxStaticText;
typedef wxControl wxTabCtrl;
typedef wxControl wxTextCtrl;
typedef wxControl wxToggleButton;
typedef wxControl wxToolBarBase;
typedef wxControl wxTreeCtrl;
typedef wxControl wxPropertyGrid;
typedef wxButton wxBitmapButton;
typedef wxBitmapButton wxContextHelpButton;
typedef wxChoice wxComboBox;
typedef wxGauge wxGauge95;
typedef wxGauge wxGaugeMSW;
typedef wxListBox wxCheckListBox;
typedef wxSlider wxSlider95;
typedef wxSlider wxSliderMSW;
typedef wxToolBarBase wxDynamicToolBar;
typedef wxToolBarBase wxToolBar;
typedef wxTreeCtrl wxRemotelyScrolledTreeCtrl;
typedef wxDialog wxColourDialog;
typedef wxDialog wxDirDialog;
typedef wxDialog wxFileDialog;
typedef wxDialog wxFindReplaceDialog;
typedef wxDialog wxFontDialog;
typedef wxDialog wxMessageDialog;
typedef wxDialog wxPageSetupDialog;
typedef wxDialog wxPrintDialog;
typedef wxDialog wxSingleChoiceDialog;
typedef wxDialog wxTextEntryDialog;
typedef wxDialog wxWizard;
typedef wxFrame wxDocChildFrame;
typedef wxFrame wxDocParentFrame;
typedef wxFrame wxHtmlHelpFrame;
typedef wxFrame wxMDIChildFrame;
typedef wxFrame wxMDIParentFrame;
typedef wxFrame wxMiniFrame;
typedef wxFrame wxPreviewFrame;
typedef wxFrame wxProgressDialog;
typedef wxFrame wxSplashScreen;
typedef wxFrame wxToolWindow;
typedef wxMDIChildFrame wxDocMDIChildFrame;
typedef wxMDIParentFrame wxDocMDIParentFrame;
typedef wxPreviewFrame ELJPreviewFrame;
//typedef wxToolWindow cbFloatedBarWindow;
typedef wxPanel wxEditableListBox;
typedef wxPanel wxNewBitmapButton;
typedef wxPanel wxPreviewControlBar;
typedef wxPanel wxScrolledWindow;
typedef wxPanel wxWizardPage;
typedef wxPreviewControlBar ELJPreviewControlBar;
typedef wxScrolledWindow wxGLCanvas;
typedef wxScrolledWindow wxGrid;
typedef wxScrolledWindow wxHtmlWindow;
typedef wxScrolledWindow wxPlotWindow;
typedef wxScrolledWindow wxPreviewCanvas;
typedef wxScrolledWindow wxSplitterScrolledWindow;
typedef wxHtmlWindow wxcHtmlWindow;
typedef wxWizardPage wxWizardPageSimple;
typedef wxPopupWindow wxPopupTransientWindow;
typedef wxPopupTransientWindow wxTipWindow;
typedef wxSashWindow wxSashLayoutWindow;
typedef wxSplitterWindow wxThinSplitterWindow;
typedef wxFileSystemHandler wxMemoryFSHandler;
typedef wxGDIObject wxBitmap;
typedef wxGDIObject wxBrush;
typedef wxGDIObject wxFont;
typedef wxGDIObject wxPalette;
typedef wxGDIObject wxPen;
typedef wxGDIObject wxRegion;
typedef wxBitmap wxCursor;
typedef wxBitmap wxIcon;
typedef wxGridTableBase ELJGridTable;
typedef wxHelpControllerBase wxHelpController;
typedef wxHelpControllerBase wxHtmlHelpController;
typedef wxHtmlCell wxHtmlColourCell;
typedef wxHtmlCell wxHtmlContainerCell;
typedef wxHtmlCell wxHtmlWidgetCell;
typedef wxHtmlParser wxHtmlWinParser;
typedef wxHtmlTagHandler wxHtmlWinTagHandler;
typedef wxList wxBrushList;
typedef wxList wxColourDatabase;
typedef wxList wxExprDatabase;
typedef wxList wxFontList;
typedef wxList wxPathList;
typedef wxList wxPenList;
typedef wxList wxStringList;
typedef wxModule wxHtmlTagsModule;
typedef wxPlotCurve ELJPlotCurve;
typedef wxPrintout ELJPrintout;
typedef wxPrintout wxHtmlPrintout;
typedef wxServerBase wxDDEServer;
typedef wxServerBase wxServer;
// typedef wxServer ELJServer;
typedef wxSizer wxBoxSizer;
typedef wxSizer wxGridSizer;
typedef wxSizer wxMultiCellSizer;
typedef wxSizer wxNotebookSizer;
typedef wxBoxSizer wxStaticBoxSizer;
typedef wxGridSizer wxFlexGridSizer;
typedef wxFlexGridSizer wxMultiCellCanvas;
typedef wxSockAddress wxIPV4address;
typedef wxSocketBase wxSocketClient;
typedef wxSocketBase wxSocketServer;
typedef wxSocketClient wxProtocol;
typedef wxProtocol wxFTP;
typedef wxProtocol wxHTTP;
typedef wxTimer wxTimerEx;
typedef wxToolLayoutItem wxDynToolInfo;
typedef wxTreeLayout wxTreeLayoutStored;
typedef wxStreamBase wxInputStream;
typedef wxStreamBase wxOutputStream;
typedef wxInputStream wxFFileInputStream;
typedef wxInputStream wxFileInputStream;
typedef wxInputStream wxFilterInputStream;
typedef wxInputStream wxMemoryInputStream;
typedef wxInputStream wxSocketInputStream;
typedef wxInputStream wxZipInputStream;
typedef wxFilterInputStream wxBufferedInputStream;
typedef wxFilterInputStream wxZlibInputStream;
typedef wxOutputStream wxCountingOutputStream;
typedef wxOutputStream wxFFileOutputStream;
typedef wxOutputStream wxFileOutputStream;
typedef wxOutputStream wxFilterOutputStream;
typedef wxOutputStream wxMemoryOutputStream;
typedef wxOutputStream wxSocketOutputStream;
typedef wxFilterOutputStream wxBufferedOutputStream;
typedef wxFilterOutputStream wxZlibOutputStream;
typedef wxThread wxInputSink;

// for dragimage.h
typedef wxDragImage wxGenericDragImage;

// for graphicscontext.h
typedef wxObject wxGraphicsObject;
typedef wxGraphicsObject wxGraphicsBrush;
typedef wxGraphicsObject wxGraphicsContext;
typedef wxGraphicsObject wxGraphicsFont;
typedef wxGraphicsObject wxGraphicsMatrix;
typedef wxGraphicsObject wxGraphicsPath;
typedef wxGraphicsObject wxGraphicsPen;
typedef wxGraphicsObject wxGraphicsRenderer;

// for glcanvas.h
// typedef wxWindow wxGLCanvas;
typedef wxObject wxGLContext;

// for sound.h

typedef wxObject wxSound;

// for mediactrl.h

typedef wxWindow wxMediaCtrl;
typedef wxNotifyEvent wxMediaEvent;

// for previewframe.h

// typedef wxFrame wxPreviewFrame;
// typedef wxPanel wxPreviewControlBar;

// for printout.h

typedef wxPrintout wxcPrintout;
typedef wxEvent wxcPrintEvent;
typedef wxEvtHandler wxcPrintoutHandler;
  
// for stc.h

typedef wxControl wxStyledTextCtrl;
typedef wxCommandEvent wxStyledTextEvent;
// typedef wxObject wxXmlResource;

// for wxcaml.idl

typedef wxGridCellTextEditor wxGridCellTextEnterEditor;
typedef wxConfigBase wxFileConfig;
