#define IDLTypeDef(tp) typedef [abstract, ptr] void *tp

IDLTypeDef(ELJDragDataObject);
IDLTypeDef(ELJMessageParameters);
IDLTypeDef(HENV);
IDLTypeDef(TextDataObject);
IDLTypeDef(wxAcceleratorEntry);
IDLTypeDef(wxAcceleratorTable);
IDLTypeDef(wxArray);
IDLTypeDef(wxBusyCursor);
IDLTypeDef(wxBusyInfo);
IDLTypeDef(wxCalendarDateAttr);
IDLTypeDef(wxCaret);
IDLTypeDef(wxClassInfo);
IDLTypeDef(wxClientData);
IDLTypeDef(wxClientDataContainer);
IDLTypeDef(wxCommandLineParser);
IDLTypeDef(wxCondition);
IDLTypeDef(wxConfigBase);
IDLTypeDef(wxCriticalSection);
IDLTypeDef(wxCriticalSectionLocker);
IDLTypeDef(wxDCClipper);
IDLTypeDef(wxDataFormat);
IDLTypeDef(wxDataInputStream);
IDLTypeDef(wxDataObject);
IDLTypeDef(wxDataOutputStream);
IDLTypeDef(wxDateTime);
IDLTypeDef(wxDb);
IDLTypeDef(wxDbColDef);
IDLTypeDef(wxDbColFor);
IDLTypeDef(wxDbColInf);
IDLTypeDef(wxDbColInfArray);
IDLTypeDef(wxDbConnectInf);
IDLTypeDef(wxDbInf);
IDLTypeDef(wxDbSqlTypeInfo);
IDLTypeDef(wxDbTable);
IDLTypeDef(wxDbTableInf);
IDLTypeDef(wxDbTableInfo);
IDLTypeDef(wxDebugContext);
IDLTypeDef(wxDialUpManager);
IDLTypeDef(wxDirTraverser);
IDLTypeDef(wxDllLoader);
IDLTypeDef(wxDropSource);
IDLTypeDef(wxDropTarget);
IDLTypeDef(wxDynamicLibrary);
IDLTypeDef(wxExpr);
IDLTypeDef(wxFFile);
IDLTypeDef(wxFileName);
IDLTypeDef(wxFileType);
IDLTypeDef(wxFontEnumerator);
IDLTypeDef(wxFontMapper);
IDLTypeDef(wxGridCellAttr);
IDLTypeDef(wxGridCellCoordsArray);
IDLTypeDef(wxGridCellWorker);
IDLTypeDef(wxHDBC);
IDLTypeDef(wxHENV);
IDLTypeDef(wxHSTMT);
IDLTypeDef(wxHashMap);
IDLTypeDef(wxHelpProvider);
IDLTypeDef(wxIconBundle);
IDLTypeDef(wxLocale);
IDLTypeDef(wxLog);
IDLTypeDef(wxLongLong);
IDLTypeDef(wxMBConv);
IDLTypeDef(wxMimeTypesManager);
IDLTypeDef(wxMutex);
IDLTypeDef(wxMutexLocker);
IDLTypeDef(wxNodeBase);
IDLTypeDef(wxObject);
IDLTypeDef(wxObjectRefData);
IDLTypeDef(wxPoint);
IDLTypeDef(wxRealPoint);
IDLTypeDef(wxRect);
IDLTypeDef(wxRegEx);
IDLTypeDef(wxScintilla);
IDLTypeDef(wxScopedArray);
IDLTypeDef(wxScopedPtr);
IDLTypeDef(wxSemaphore);
IDLTypeDef(wxSingleInstanceChecker);
IDLTypeDef(wxSize);
IDLTypeDef(wxStopWatch);
IDLTypeDef(wxStreamBase);
IDLTypeDef(wxStreamBuffer);
IDLTypeDef(wxStreamToTextRedirector);
IDLTypeDef(wxString);
IDLTypeDef(wxStringBuffer);
IDLTypeDef(wxTempFile);
IDLTypeDef(wxTextAttr);
IDLTypeDef(wxTextFile);
IDLTypeDef(wxTextInputStream);
IDLTypeDef(wxTextOutputStream);
IDLTypeDef(wxThread);
IDLTypeDef(wxTimeSpan);
IDLTypeDef(wxTimerRunner);
IDLTypeDef(wxTipProvider);
IDLTypeDef(wxTreeItemId);
IDLTypeDef(wxWindowDisabler);

// typedef [ptr, mltype("WxClosure.t")] void* wxClosure;
IDLTypeDef(wxClosure);

// for managed.h
IDLTypeDef(wxManagedPtr); 

// for stc.h
IDLTypeDef(wxSTCDoc);
IDLTypeDef(wxMemoryBuffer);


 
