wxObject null_object (void);
int wxcMessageBox(TClass(wxString) message,
		      TClass(wxString) caption,
		      long style,
		      TClass(wxWindow) parent,
		      int x, int y);


[string]char* wxString_GetUtf8(wxString s);
TClass(wxString) wxString_CreateUTF8( TString buffer );
